### ISSUE TITLE
Add support for list view

### ISSUE THREAD

**Issue by Level3Manatee** [Clorith/blockeditor-fullscreen-mode-control#1]
It would be great to have an option for the list view open by default.

In newer Gutenberg versions it supports drag and drop, so it has become quite useful and always reopening it is a pain.

**Comment by Clorith** [comment]
Hiya, I'm not quite sure I understand what you mean by list view, do you have a screenshot or similar which could help clarify a bit?

**Comment by Level3Manatee** [comment]
Sure, see for example [https://wptavern.com/gutenberg-11-1-adds-drag-and-drop-support-for-list-view-and-upgrades-block-borders](https://wptavern.com/gutenberg-11-1-adds-drag-and-drop-support-for-list-view-and-upgrades-block-borders)

**Comment by Clorith** [comment]
Sorry about the late followup, I took the holiday weeks off, and have had to catch up.

I had a look at what you referenced here, but I am afraid that's outside of scope for this plugin. The view you are referencing isn't truly a user setting, but rather a secondary editor flow, and although I can understand that it's very useful for many, it isn't something WordPress normally stores the open/closed state of in the first place.

As that's the case, I'm closing this ticket for now, but I would encourage re-opening, or making a new ticket, if that should ever change in the future!
